export const Lang = {
  storeInfo: 'Store info',
  name: 'Name',
  address: 'Address',
  phone: 'Phone',
  redInvoiceInfo: 'Red invoice info',
  companyName: 'Company Name',
  mst: 'MST',
  editProfile: 'Edit Profile',
  deliveryMessage: 'Delivery default message',
  writeYourMessage: 'Write your message',
  update: 'Update',
  editStoreProfile: 'Edit store profile',
  remove: 'Remove',
  uploadImage: 'Upload image',
  storeName: 'Store name',
  district: 'District',
  city: 'City',
  storeAddress: 'Store address',
  companyAddress: 'Company address',
  save: 'Save',
  cancel: 'Cancel',
  basicInfo: 'Basic info',
  ok: 'OK',
  saveSuccess: 'Save success',
  incorrectPhoneFormat: 'Error',
  messagePhoneFormat: 'Format phone should be (XXX) XXX-XXXX',
}
